### ISSUE TITLE
Unexpected keyword argument for `HTTPFactory`

### ISSUE THREAD

**Issue by ka7eh** [django/daphne#148]
Running `./manage.py runserver` with daphne 1.4.0 throws the following error:

```
File "/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 228, in wrapper
  fn(*args, **kwargs)
File "/venv/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 100, in inner_run
  websocket_handshake_timeout=self.websocket_handshake_timeout,
File "/venv/lib/python3.5/site-packages/daphne/server.py", line 101, in run
    websocket_handshake_timeout=self.websocket_handshake_timeout
TypeError: __init__() got an unexpected keyword argument 'proxy_forwarded_proto_header'
```
Looking at `daphne.http_protocol.HTTPFactory` shows it doesn't accept `proxy_forwarded_proto_header` as argument.

**Comment by andrewgodwin** [comment]
My bad, I must have had a bad merge somewhere. Fixed in 1.4.1.
