### ISSUE TITLE
Did daphne3 no longer support djanfgo 2.2.x?

### ISSUE THREAD

**Issue by Taikono-Himazin** [django/daphne#340]
Thank you for updating daphne.
I updated daphne to 3, but it no longer works with the daphne 2.2.16 I was using.
Specifically, the following error is displayed.
![image](https://user-images.githubusercontent.com/25480502/97672308-279ab400-1acd-11eb-8cd0-beb42885427c.png)

Also, the following message appears in the python log.
Some parts have been replaced with <***>.

[ERROR] 2020-10-30 16: 25: 24,495 Traceback (most recent call last):
   File "<***> \ site-packages \ daphne \ http_protocol.py", line 180, in process
     "server": self.server_addr,
TypeError: __call__ () got an unexpected keyword argument'receive'
  daphne.http_protocol None
[ERROR] 2020-10-30 16: 25: 24,496 HTTP GET <***> 500 [0.00, 127.0.0.1:52918] django.channels.server 127.0.0.1:52918

If it is a bug, please fix it.
If it doesn't, I think django> = 3 should be required.

**Comment by Taikono-Himazin** [comment]
Supplement:
I lowered daphne to 2.5.0 without changing any other settings and it worked fine.

**Comment by carltongibson** [comment]
Hi @Taikono-Himazin Thanks of the report. 

Channels v3 (coming in the next few days) works with Daphne 3, but this should still work. It looks the ASGI v3 fallback is not working properly. I need to get the Channels release out, and then I'lll see if I can look into it. 

Until I can work out why the fallback isn't working, yes, if you're on Channels 2 pin to 2.5.0.

**Comment by Taikono-Himazin** [comment]
Do you mean that daphne should be 3.0.0 and channels should be 3 at the same time?
Certainly, with daphne 3.0.0 and channels 3.0.0, it works with django 2.2.16.

**Comment by carltongibson** [comment]
HI @Taikono-Himazin. 

Channels 3 requires Daphne 3. 

But unless we can't make it work (which we should be able to) Daphne 3 should still be able to run a Channels 2 project. 
I need to have a look at why that's not working. 

It's not the end of the world if we can't get it to work: 

> Until I can work out why the fallback isn't working, yes, if you're on Channels 2 pin to 2.5.0.

But I'll have a look when I get a moment.

**Comment by Taikono-Himazin** [comment]
So that's it.
Even with Django 2.2.16
Channels2 + Daphne2 = OK
Cahnnels2 + Daphne3 = OK
Cahnnels3 + Daphne2 = NG
Cahnnels3 + Daphne3 = OK
Does that mean that?
I would like to use Daphne 3 with Channels 2 if possible for compatibility.

If there are additional messages that could be shared, share them.
Is there anything I should do?

**Comment by carltongibson** [comment]
Yes, that grid is the intention. 

The only value that should not work is Channels 3 with Daphne 2 — but your report suggests there’s an issue with Channels 2 with Daphne 3. I’ll look into that when I can, but also happy if you want to dig further. 

Thanks!

**Comment by carltongibson** [comment]
I'm going to close this since Django 2.2 is EOL. The next Channels release this summer will make Django 3.2 the minimum supported version.
