### ISSUE TITLE
Channels and whole app doesn't work on daphne >= 1.0.2

### ISSUE THREAD

**Issue by darklow** [django/daphne#85]
Everything works under channels==1.0.1 and daphne 1.0.1

However I tried updating channels to 1.0.3 and daphne to 1.0.3 and app doesn't work any more, all I am seeing in console is repeating every 5 seconds:
```
2017-02-14 17:37:35,850 - ERROR - server - Error at trying to receive messages: 'RedisChannelLayer' object has no attribute 'receive'
```

So I narrowed down versions and even if I stay on channels 1.0.1 as soon as I upgrade to daphne 1.0.2, no matter what channels version, I got the same error and whole Django app doesn't even start. Last working daphne is 1.0.1 Also tried flushing redis db. Doesn't changed anything.

Mac, Python 2.7.10
Twisted==17.1.0 (Also tried Twisted 16.6.0)
django-redis==4.3.0
redis==2.10.5

**Comment by darklow** [comment]
Started working once I updated `asgi-redis`, maybe it should force specific version of `asgi-redis` for `daphne` 1.0.2

**Comment by andrewgodwin** [comment]
Unfortunately I can't make daphne depend on asgi_redis in case you're not using it, but yes, you need 1.0.0 of asgi_redis or above.
