### ISSUE TITLE
Cannot install daphne on Windows 10 using Python 3.9

### ISSUE THREAD

**Issue by TheMrAI** [django/daphne#358]
Daphne installation fails on Windows 10 with error log:
```text
[pipenv.exceptions.InstallError]:     iocpsupport.c
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(2229): warning C4047: '=': '__pyx_t_11iocpsupport_HANDLE' differs in levels of indirection from 'HANDLE'
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(2377): warning C4022: 'CreateIoCompletionPort': pointer mismatch for actual parameter 1
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(2377): warning C4022: 'CreateIoCompletionPort': pointer mismatch for actual parameter 2
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(2377): warning C4047: '=': '__pyx_t_11iocpsupport_HANDLE' differs in levels of indirection from 'HANDLE'
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(2492): warning C4022: 'GetQueuedCompletionStatus': pointer mismatch for actual parameter 1
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(2838): warning C4022: 'PostQueuedCompletionStatus': pointer mismatch for actual parameter 1
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(2949): warning C4022: 'CloseHandle': pointer mismatch for actual parameter 1
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(3292): warning C4996: 'PyObject_AsReadBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(4932): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(5149): warning C4996: 'PyObject_AsReadBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(5786): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6146): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6164): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6182): warning C4996: 'PyObject_AsWriteBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(6509): warning C4996: 'PyObject_AsReadBuffer': deprecated in 3.0
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7614): error C2039: 'tp_print': is not a member of '_typeobject'
[pipenv.exceptions.InstallError]:     C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.752.0_x64__qbz5n2kfra8p0\include\cpython/object.h(193): note: see declaration of '_typeobject'
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(8421): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
[pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(8437): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
[pipenv.exceptions.InstallError]:     error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
[pipenv.exceptions.InstallError]:     ----------------------------------------
[pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: 'C:\Users\newba\.virtualenvs\gate-I5rKKTqC\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\newba\\AppDa
ta\\Local\\Temp\\pip-install-luvlnumu\\twisted_11ca60c4a6574df3bace45a41836d7af\\setup.py'"'"'; __file__='"'"'C:\\Users\\newba\\AppData\\Local\\Temp\\pip-install-luvlnumu\\twisted_11ca60c4a6574df3bace45a41836d7af\\setup.py'"'"'
;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\newba\AppData\Local\Temp\pip-record-nq
mmzdek\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\newba\.virtualenvs\gate-I5rKKTqC\include\site\python3.9\twisted' Check the logs for full command output.
ERROR: Couldn't install package: twisted
 Package installation failed...
     ================================ 0/1 - 00:00:27
```

The issue is with: [pipenv.exceptions.InstallError]:     src/twisted/internet/iocpreactor/iocpsupport/iocpsupport.c(7614): error C2039: 'tp_print': is not a member of '_typeobject'
As I understand **tp_print** was dropped from Python 3.9 version of CPython, that is why it cannot see it.

Checked and daphne does work with Python 3.9 on a Linux-based system like the one provided in the [Python docker image](https://hub.docker.com/_/python), according to the doc Debian.

The pipfile I am using:
```python
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "*"
coverage = "*"
psycopg2 = "*"
daphne = "*"

[dev-packages]

[requires]
python_version = "3.9"
```

**Comment by carltongibson** [comment]
Looks like a twisted issue. Did you search for an issue there?

**Comment by TheMrAI** [comment]
Indeed it is. In detail [here](https://stackoverflow.com/questions/66186136/pip-install-twister-throws-really-long-error).

In short the issue is that Twisted doesn't support Python 3.9 on windows yet, either Python 3.8 has to be used on windows or a new release of Twisted.

**Comment by carltongibson** [comment]
Super. Thanks for the follow up! 

I'm going to close here, as there's nothing we can do here, rather than contribute there.
